output_dir = "outputs/rl-nemotron-debug"
clean_output_dir = true
max_steps = 500
seq_len = 4096

[slurm]
job_name = "nemotron-sami-debug"

[deployment]
type = "multi_node"
num_train_nodes = 2
num_infer_nodes = 2

[log]
level = "debug"

[wandb]
project = "nemotron_sami_debug"
name = "nemotron-120b-math"
shared = true

[weight_broadcast]
type = "nccl"

[model]
name = "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16"

[trainer.model]
impl = "custom"
attn = "flash_attention_2"
optim_cpu_offload = true
fused_lm_head_token_chunk_size = 8192

[trainer.model.debug]
random_init = true
num_layers = 8

[trainer.model.ac_offloading]
max_inflight_activations = 5

[trainer.model.ac]
freq = 1

[trainer.model.compile]

[orchestrator]
batch_size = 512
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 4096

[[orchestrator.env]]
id = "math-env"
name = "hendrycks-math"
args = { dataset_name = "PrimeIntellect/Hendrycks-Math", dataset_subset = "default", math_verify_max_workers = 128, math_verify_timeout = 60 }

[orchestrator.buffer]
easy_threshold = 1.0
hard_threshold = 0.0

[orchestrator.eval]
interval = 10

[orchestrator.eval.sampling]
max_tokens = 4096

[[orchestrator.eval.env]]
id = "math500"
num_examples = 30
rollouts_per_example = 4

[inference.parallel]
tp = 4
dp = 4
