max_steps = 100
seq_len = 2048

[wandb]
project = "alphabet-sort-debug"
name = "alphabet-sort"


[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[orchestrator]
batch_size = 512
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 512

[[orchestrator.env]]
id = "alphabet-sort"
name = "alphabet-sort"
args = { min_turns = 2, max_turns = 2 }

[orchestrator.eval]
interval = 50

[[orchestrator.eval.env]]
id = "alphabet-sort"
name = "alphabet-sort"
num_examples = 50
rollouts_per_example = 4
args = { min_turns = 2, max_turns = 2 }

[trainer]

[inference]