output_dir = "/data/sami_debug/nemotron-debug"
clean_output_dir = true
max_steps = 5
seq_len = 2048

[slurm]
job_name = "nemotron-4node"
pre_run_command = "uv sync --all-extras --group mamba-ssm"

[deployment]
type = "multi_node"
num_train_nodes = 4
num_infer_nodes = 4

[log]
level = "debug"

[wandb]
project = "sami_debug_nemotron"
name = "nemotron-120b-math"
shared = true

[weight_broadcast]
type = "nccl"

[model]
name = "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16"

[trainer]
dist_timeout_seconds = 1800

[trainer.model]
impl = "custom"
attn = "flash_attention_2"
optim_cpu_offload = true
ep = 8
fused_lm_head_token_chunk_size = 8192

[trainer.model.ac]
freq = 1

[trainer.model.ac_offloading]
max_inflight_activations = 5

[trainer.model.compile]

[orchestrator]
batch_size = 128
rollouts_per_example = 8

[orchestrator.sampling]
max_tokens = 2048

[[orchestrator.env]]
id = "math-env"
name = "hendrycks-math"
args = { dataset_name = "PrimeIntellect/Hendrycks-Math", dataset_subset = "default", math_verify_max_workers = 128, math_verify_timeout = 60 }

[orchestrator.buffer]
easy_threshold = 1.0
hard_threshold = 0.0

[orchestrator.eval]
interval = 10

[orchestrator.eval.sampling]
max_tokens = 2048

[[orchestrator.eval.env]]
id = "math500"
num_examples = 30
rollouts_per_example = 4

[inference.parallel]
tp = 8
dp = 1
