max_steps = 20
seq_len = 2048

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"

[orchestrator]
batch_size = 128
rollouts_per_example = 16

[orchestrator.train.sampling]
max_completion_tokens = 128

[[orchestrator.train.env]]
id = "reverse-text"

[orchestrator.train.env.sampling]
max_completion_tokens = 127

[[orchestrator.train.env]]
id = "reverse-text"
name = "reverse-text-2"

[orchestrator.eval]
interval = 5

[orchestrator.eval.sampling]
max_completion_tokens = 512

[[orchestrator.eval.env]]
id = "reverse-text"
name = "eval-default"
num_examples = 32
rollouts_per_example = 4

[[orchestrator.eval.env]]
id = "reverse-text"
name = "eval-custom"
num_examples = 16
rollouts_per_example = 2

[orchestrator.eval.env.sampling]
max_completion_tokens = 256
temperature = 0.5

[trainer.optim]
lr = 3e-6

[inference] # Default inference config