inference_gpu_ids = [0,1]
trainer_gpu_ids = [2,3]

max_steps = 2000
seq_len = 4096

[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[wandb]
project = "rl_srini_2026"
name = "agent_search_2000_steps"

[trainer.optim]
lr=1e-5
weight_decay=0.0

[trainer.model.lora]
rank = 16
dropout = 0.0
target_modules = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj"
]

[orchestrator]
batch_size = 16
rollouts_per_example = 16
oversampling_factor = 2.0

[orchestrator.client]
timeout = 120

[orchestrator.model.lora]
name = "qwen3-4b-agent_search"

[orchestrator.sampling]
max_tokens = 4096

[orchestrator.buffer]
online_difficulty_filtering = true

[[orchestrator.env]]
id = "agent_search"
args = { judge_model = "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4", judge_base_url = "http://localhost:6379/v1", judge_api_key = "abc"}

[ckpt] # Checkpoint at the end of training



[inference.model]
enable_auto_tool_choice = true
tool_call_parser = "hermes"
max_model_len = 16384
