max_steps = 3000
seq_len =  8192


[deployment]
num_infer_gpus = 1
num_train_gpus = 1


[model]
name = "./agent_search_qwen3-0.6B-SFT/"



[wandb]
project = "rl_srini_2026"
name = "agent_search_post_sft_post_rl_phase1"

[trainer.optim]
lr=3e-5
weight_decay=0.0

[trainer.scheduler]
type = "cosine"
warmup_steps = 200
min_lr = 0.0


[trainer.model.lora]
rank = 16
dropout = 0.0
target_modules = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj"
]

[orchestrator]
batch_size = 16
rollouts_per_example = 16
oversampling_factor = 1.0


[orchestrator.model.lora]
name = "qwen3-4b-agent_search"

[orchestrator.train.sampling]
max_tokens = 512

[orchestrator.buffer]
online_difficulty_filtering = true
easy_threshold = 1.0
hard_threshold = 0.0
seed = 42

[[orchestrator.train.env]]
id = "agent_search"
args = { judge_model = "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4", judge_base_url = "http://localhost:8001/v1", judge_api_key = "abc", judge_timeout = 30.0, judge_max_retries = 0, judge_max_concurrent = 2 }


[orchestrator.eval]
interval = 30
num_examples = 16
rollouts_per_example = 3


[[orchestrator.eval.env]]
id = "agent_search"
args = { judge_model = "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4", judge_base_url = "http://localhost:8001/v1", judge_api_key = "abc", judge_timeout = 30.0, judge_max_retries = 0, judge_max_concurrent = 2 }


[inference.server]
port = 8002

[orchestrator.client]
base_url = ["http://localhost:8002/v1"]
timeout = 120


[inference.model]
tool_call_parser = "hermes"
max_model_len = 16384

[ckpt]
interval = 30
keep_last = 1
